ALTER TABLE history
PARTITION BY RANGE (clock) (
    PARTITION p2023_01_01 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m-%d') )),
    PARTITION p2023_01_02 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m-%d') ))
    -- 添加更多分区...

);

ALTER TABLE history_log
PARTITION BY RANGE (clock) (
    PARTITION p2023_01_01 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m-%d') )),
    PARTITION p2023_01_02 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m-%d') ))
    -- 添加更多分区...

);

ALTER TABLE history_str
PARTITION BY RANGE (clock) (
    PARTITION p2023_01_01 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m-%d') )),
    PARTITION p2023_01_02 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m-%d') ))
    -- 添加更多分区...

);

ALTER TABLE history_text
PARTITION BY RANGE (clock) (
    PARTITION p2023_01_01 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m-%d') )),
    PARTITION p2023_01_02 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m-%d') ))
    -- 添加更多分区...

);

ALTER TABLE history_uint
PARTITION BY RANGE (clock) (
    PARTITION p2023_01_01 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m-%d') )),
    PARTITION p2023_01_02 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m-%d') ))

);



ALTER TABLE trends
PARTITION BY RANGE  (clock) (
    PARTITION p2023_01 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m') ))

    -- 添加更多分区...

);

ALTER TABLE trends_uint
PARTITION BY RANGE (clock) (
    PARTITION p2022_12 VALUES LESS THAN (UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 YEAR), '%Y-%m') ))

    -- 添加更多分区...

);
